### ISSUE TITLE
Improvements to "about" description of the repo

### ISSUE THREAD

**Issue by tonnitommi** [joseferrerh/invoices-leanautomation#1]
Hi @joseferrerh. Greetings from Robocorp, and thanks for contributing to the community of digital workers! :)

I noticed the About description of the repository is not optimal. Because the Portal pulls in the description from "About", it ends up looking like this:

![image](https://user-images.githubusercontent.com/40179958/182413897-61b9c091-b4fa-479d-a16b-cadded1b829d.png)

We suggest improving the about description in the repo so that it is a short and clear complete sentence. Thank you!

**Comment by joseferrerh** [comment]
Thanks Tommi, I will have a look at it

**Comment by joseferrerh** [comment]
This has been fixed.
Thank you very much for the feedback

![image](https://user-images.githubusercontent.com/59340804/182851633-cd270bec-15b6-4675-81ee-38eb21efe033.png)
